// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAahYVpyPj0g83nXHq8btA-ZriKD-2gAsU',
    appId: '1:29540370954:web:c2115fa6a3e0db8619adf3',
    messagingSenderId: '29540370954',
    projectId: 'kidsworld-48ee4',
    authDomain: 'kidsworld-48ee4.firebaseapp.com',
    databaseURL: 'https://kidsworld-48ee4-default-rtdb.firebaseio.com',
    storageBucket: 'kidsworld-48ee4.appspot.com',
    measurementId: 'G-HN3Z1PFFQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJCnqQL04Mjn5pmDnGEMs8wLsjsZM03ik',
    appId: '1:29540370954:android:3536f9a96afcef9319adf3',
    messagingSenderId: '29540370954',
    projectId: 'kidsworld-48ee4',
    databaseURL: 'https://kidsworld-48ee4-default-rtdb.firebaseio.com',
    storageBucket: 'kidsworld-48ee4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxX2kwp9aoIFg5qH-cGWao4oiAP0UVjFM',
    appId: '1:29540370954:ios:cce1021ff281823419adf3',
    messagingSenderId: '29540370954',
    projectId: 'kidsworld-48ee4',
    databaseURL: 'https://kidsworld-48ee4-default-rtdb.firebaseio.com',
    storageBucket: 'kidsworld-48ee4.appspot.com',
    iosClientId: '29540370954-sh8nil27mdf9cvpso5i7pf3c4tbh47vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.kidsworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxX2kwp9aoIFg5qH-cGWao4oiAP0UVjFM',
    appId: '1:29540370954:ios:cce1021ff281823419adf3',
    messagingSenderId: '29540370954',
    projectId: 'kidsworld-48ee4',
    databaseURL: 'https://kidsworld-48ee4-default-rtdb.firebaseio.com',
    storageBucket: 'kidsworld-48ee4.appspot.com',
    iosClientId: '29540370954-sh8nil27mdf9cvpso5i7pf3c4tbh47vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.kidsworld',
  );
}
